version: '3'
services:
    nodejs:
        image: nexus_backend
        container_name: backend_nexus
        restart: unless-stopped
        env_file: .env
        ports:
            - '3030:3000'
        links:
            - postgres
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - '6500:5432'
        volumes:
            - progresDB:/var/lib/postgresql/data
        env_file:
            - ./.env
    pgAdmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        env_file:
            - ./.env
        ports:
            - '5050:80'
volumes:
    progresDB:
